
CREATE TABLE DEPT (
 DNO NUMBER(2,0) NOT NULL,
 DNAME VARCHAR2(14) CONSTRAINT UK_DEPT_DNAME UNIQUE,
 LOC VARCHAR2(13)
);

-- SQLD 대비
-- 테이블 만든 후에 제약조건 걸기
-- 삭제 후 재생성해서 실습하세요
DROP TABLE DEPT;

CREATE TABLE DEPT (
 DNO NUMBER(2,0) ,
 DNAME VARCHAR2(14),
 LOC VARCHAR2(13)
);

ALTER TABLE DEPT
ADD CONSTRAINT UK_DEPT_DNAME UNIQUE(DNAME);

ALTER TABLE DEPT 
MODIFY DNO NUMBER(2,0) NOT NULL;