
CREATE TABLE DEPT (
 DNO NUMBER(2,0) CONSTRAINT PK_DEPT PRIMARY KEY,
 DNAME VARCHAR2(14),
 LOC VARCHAR2(13)
);

-- PK 테스트 : 
INSERT INTO DEPT(ID, PWD,NAME,PHONE,ADDRESS)
VALUES(NULL,NULL,NULL,'010-123-4567','부산시');

-- SQLD 대비
-- 제약조건명 : PK_DEPT_COPY_DNO(*)
-- 사용법) ALTER TABLE 테이블명
--        ADD CONSTRAINT 제약조건명 PRIMARY KEY(컬럼)
DROP TABLE DEPT;

CREATE TABLE DEPT (
 DNO NUMBER(2,0),
 DNAME VARCHAR2(14),
 LOC VARCHAR2(13),
 CONSTRAINT PK_DEPT PRIMARY KEY(DNO)
);

DROP TABLE DEPT;

CREATE TABLE DEPT (
 DNO NUMBER(2,0),
 DNAME VARCHAR2(14),
 LOC VARCHAR2(13)
);
ALTER TABLE DEPT
ADD CONSTRAINT PK_DEPT PRIMARY KEY(DNO);

