
CREATE TABLE DEPT (
 DNO NUMBER(2,0) CONSTRAINT PK_DEPT PRIMARY KEY,
 DNAME VARCHAR2(14),
 LOC VARCHAR2(13)
);

-- PK 테스트 : 1) UNIQUE(유일) 2) NOT NULL
-- CUSTOMER3 : INSERT (ID) 컬럼에 NULL 값을 넣기
-- 결론 : PK 때문에 에러발생
INSERT INTO DEPT(ID, PWD,NAME,PHONE,ADDRESS)
VALUES(NULL,NULL,NULL,'010-123-4567','부산시');

-- SQLD 대비
-- 제약조건명 : PK_DEPT_COPY_DNO(*)
-- 사용법) ALTER TABLE 테이블명
--        ADD CONSTRAINT 제약조건명 PRIMARY KEY(컬럼)
ALTER TABLE DEPT
ADD CONSTRAINT PK_DEPT PRIMARY KEY(DNO);

CREATE TABLE DEPT (
 DNO NUMBER(2,0),
 DNAME VARCHAR2(14),
 LOC VARCHAR2(13),
 CONSTRAINT PK_DEPT PRIMARY KEY(DNO)
);

