-- 간단연습 : CUSTOMER4 테이블을 정의하고 ID 컬럼에 PK 제약조건을 지정하세요
-- 제약조건이름(중복 금지) : PK_CUSTOMER4_ID 
-- (ID       VARCHAR2(20)
--  PWD     VARCHAR2(20)
--  NAME    VARCHAR2(20)
--  PHONE   VARCHAR2(30)
-- ADDRESS VARCHAR2(1000))
CREATE TABLE CUSTOMER4 (
 ID VARCHAR2(20) CONSTRAINT PK_CUSTOMER4 PRIMARY KEY,
 PWD VARCHAR2(20),
 NAME VARCHAR2(20),
 PHONE VARCHAR2(30),
);