-- 간단연습 : EMP_SECOND2 부모테이블은 DEPARTMENT 이고,
--           DNO (부서번호) 컬럼에 FK 를 생성해 주세요
--         ENO NUMBER(4) (기본키 #2)
--         ENAME VARCHAR2(10), 
--         JOB VARCHAR2(9)
--         DNO NUMBER(2) (참조키 : 부모(DEPARTMENT)) 지정하세요
-- 단 PK 이름은: PK_EMP3,  FK 이름은 : FK_EMP3_DNO
CREATE TABLE EMP3 (
    ENO NUMBER(4) CONSTRAINT PK_EMP3 PRIMARY KEY,
    ENAME VARCHAR2(10), 
    JOB VARCHAR2(9),
    DNO NUMBER(2),
    CONSTRAINT FK_EMP3_DNO
    FOREIGN KEY(DNO) REFERENCES DEPARTMENT(DNO)
);

ALTER TABLE EMP3
ADD CONSTRAINT FK_EMP3_DNO
FOREIGN KEY(DNO) REFERENCES DEPARTMENT(DNO);