-- 간단연습 : EMP_SECOND2 부모테이블은 DEPARTMENT 이고,
--           DNO (부서번호) 컬럼에 FK 를 생성해 주세요
--         ENO NUMBER(4) (기본키 #2)
--         ENAME VARCHAR2(10), 
--         JOB VARCHAR2(9)
--         DNO NUMBER(2) (참조키 : 부모(DEPARTMENT)) 지정하세요
-- 단 FK 이름은 : FK_EMP_SECOND2_DNO
CREATE TABLE EMP_SECOND2 (
    ENO NUMBER(4) CONSTRAINT PK_EMP_SECOND2_ENO PRIMARY KEY,
    ENAME VARCHAR2(10), 
    JOB VARCHAR2(9),
    DNO NUMBER(2),
);
ALTER TABLE EMP_SECOND2
ADD CONSTRAINT FK_EMP_SECOND2_DNO
FOREIGN KEY(DNO) REFERENCES DEPARTMENT(DNO);