SELECT TO_CHAR(HIREDATE, 'YYYY-MM-DD HH24:MI:SS') AS 입사일
FROM EMPLOYEE;

SELECT TRUNC(SYSDATE - TO_DATE('2024/01/01', 'YYYY/MM/DD')) AS 지난일수
FROM DUAL;

SELECT NVL(MANAGER, 0) AS 관리자사번 
FROM EMPLOYEE;