-- 1)
SELECT D.DNO, D.DNAME
FROM   EMPLOYEE   E
      ,DEPARTMENT D
WHERE E.DNO = D.DNO
AND   E.ENAME = 'SCOTT';


-- 2) 
SELECT E.ENAME, 
       D.DNAME,
       D.LOC
FROM EMPLOYEE   E
    ,DEPARTMENT D
WHERE E.DNO = D.DNO;

-- 3) 
SELECT E.*, D.*
FROM EMPLOYEE   E
    ,DEPARTMENT D
WHERE E.DNO = D.DNO
AND   D.DNO = 10;