-- 7
SELECT ENAME, JOB
FROM EMPLOYEE
WHERE JOB = (SELECT JOB
            FROM EMPLOYEE
            WHERE ENO = 7788);
--8
SELECT ENAME, JOB
FROM EMPLOYEE
WHERE SALARY > (SELECT SALARY
                FROM EMPLOYEE
                WHERE ENO = 7499);

-- 9
SELECT ENAME, JOB, SALARY
FROM EMPLOYEE
WHERE SALARY = (SELECT MIN(SALARY)
                FROM EMPLOYEE);