-- 예제 2) 테이블에 insert 할때 시퀀스 사용하기
-- 실습테이블 : 부서(DEPARTMENT) -> DEPT_TEMP
CREATE TABLE DEPT
AS
SELECT * FROM DEPARTMENT
WHERE 1=2;

-- INSERT : 시퀀스
INSERT INTO DEPT(DNO, DNAME, LOC)
VALUES(SAMPLE_SEQ2.NEXTVAL, '개발부', '대전');

COMMIT;