-- 이름 자유롭게 만들기: c## 안붙이기
ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER SCOTT IDENTIFIED BY "!Ds1234567890"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SYNONYM TO SCOTT;
GRANT UNLIMITED TABLESPACE TO SCOTT;