-- 이름 자유롭게 만들기: c## 안붙이기
ALTER SESSION SET "_ORACLE_SCRIPT"=true;

-- 주석 : CTRL + /
-- 예제1) 계정만들기
-- 사용법 : 
-- CREATE USER 계정명 IDENTIFIED BY 암호
-- DEFAULT TABLESPACE 작업공간(USERS)
-- TEMPORARY TABLESPACE 임시공간(TEMP);
CREATE USER SCOTT IDENTIFIED BY "!Ds1234567890"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

-- 예제2) 권한 부여 : 접속, DB 테이블 사용권한 
-- 나중 자세히 권한 설명 : 챕터 따로 있음
-- 사용법) GRANT 권한명,권한명2... TO 계정명;
GRANT CONNECT, RESOURCE, CREATE VIEW TO SCOTT;
GRANT UNLIMITED TABLESPACE TO SCOTT;