-- 간단연습 : 사원 : EMP , 테이블 주석, 컬럼 주석 을 만들어 주세요
-- 참고 : EMPLOYEE 테이블의 테이블/컬럼 주석과 똑같이 해주세요
-- 테이블 주석 : 사원정보
COMMENT ON TABLE EMP IS '사원정보';

COMMENT ON COLUMN EMP.ENO IS '사원번호';
COMMENT ON COLUMN EMP.ENAME IS '부서명';
COMMENT ON COLUMN EMP.JOB IS '직위';
COMMENT ON COLUMN EMP.MANAGER IS '관리자';
COMMENT ON COLUMN EMP.HIREDATE IS '입사일';
COMMENT ON COLUMN EMP.SALARY IS '월급';
COMMENT ON COLUMN EMP.COMMISSION IS '상여금';
COMMENT ON COLUMN EMP.DNO IS '부서번호';